config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'contacts#index'

  resources :contacts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end

  def new
    @contacts = Contact.new
  end

  def create
    @contacts = Contact.new(contact_params)

    if @contact.save
      redirect_to contact_url(@contact), notice: "contact was successfully created." 
    else
      render :new, status:  :unprocessable_entity 
    end

  end
  
  private
  
    def contact_params
      params.require(:Contact).permit(:name, :phone_number, :email)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contacts/_form.html.slim
= form_with(model: contact, local: true) do |form|

  - if contact.errors.any?
    div[style="color: red"]
      h2
        = pluralize(contact.errors.count, "error")
        |  prohibited this contact from being saved:
      ul
        - contact.errors.each do |error|
          li
            = error.full_message
  .card
    .card-body.p-lg-15
      .mb-13
        .row.mb-7
          label.col-lg-4.fw-semibold.text-muted
            = form.label :name
          .col-lg-8
            span.fw-bold.fs-6.text-gray-800
               = form.text_field :name
        .row.mb-7
          label.col-lg-4.fw-semibold.text-muted
            = form.label :phone_number
          .col-lg-8
            span.fw-bold.fs-6.text-gray-800
               = form.text_field :phone_number
        .row.mb-7
          label.col-lg-4.fw-semibold.text-muted
            = form.label :email
          .col-lg-8
            span.fw-bold.fs-6.text-gray-800
               = form.text_field :email
  .actions
    = form.submit class: "btn btn-sm fw-bold btn-success me-2 mb-2"

app/views/contacts/index.html.slim
h1
  | Hello word Bruno

app/views/contacts/new.html.slim
h1
  | New Contacts 

= render 'form', contact: @contact

= link_to 'Back', contacts_path, class: "btn btn-sm fw-bold btn-secondary me-2 mb-2"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>